### PR TITLE
🔥 remove all upload methods

### PR DESCRIPTION
**Pull request by boredland**
They aren't used anywhere as far as I know (did go through lots of repos).

Complexity like this should be implemented on the users side.

closes https://github.com/manjaro/manjaro-iso-action/issues/22 as a side-effect

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Don't get it. `upload-cdn77-s3` is used for the stable ISOs to upload to our CDN network. Also the sourceforge upload.

**Comment by philmmanjaro** [comment]
Those I use to build the stable ISOs which can be found here:

https://github.com/manjaro/citestbed/blob/master/.github/workflows/iso_build.yaml
https://github.com/manjaro/citestbed/blob/master/.github/workflows/iso_build_lts.yaml

They are used for the stable ISO files.

**Comment by boredland** [comment]
`citestbed` isn't a testbed, but uploads our stable images? wow.

**Comment by romangg** [comment]
IMO we need better docs about what repos there are all and then in general reducing the number of them. It can't be, that it's so difficult to work with them.

Can we find some time after stable snap to discuss that more @philmmanjaro? Also then we can hopefully remerge the PR here, at least the parts of it which remove stuff taht are really not needed anymore.

**Comment by philmmanjaro** [comment]
CDNs don't list the images so a review is done on those images. Sourceforge is only optional and not promoted when we do a release.

**Comment by boredland** [comment]
by the way, the only docs in that "testbed" repo:

> here we test some CI ideas

**Comment by philmmanjaro** [comment]
There are some outdated upload methods we don't use anymore, but s3 and sf is still used.

**Comment by philmmanjaro** [comment]
@oberon-manjaro Can you check again which lines for CDN77 upload is not needed anymore? I think we can drop OSDN upload as we don't use that for ages. SF is still our backup for download archives, even they always send emails that we use too much storage on their end ...

**Pull request merged**
