### PR TITLE
fixup: use curl instead of wget

### PR DESCRIPTION
**Pull request by pheiduck**
curl allows you to ask HTTP and HTTPS servers to provide compressed versions of the data and then perform automatic decompression of it on arrival. In situations where bandwidth is more limited than CPU this will help you receive more data in a shorter amount of time.

URL: https://everything.curl.dev/usingcurl/downloads/compression

### CODE REVIEW

**Comment by pheiduck** [comment]
https://github.com/manjaro-kernels/kernel-action/pull/7

**Comment by boredland** [comment]
This looks fine, but perhaps I am missing the point. What triggers that change? Is there a realy use-case where sb builds the kernel/isos with sparse bandwith? Is that even possible, as buildiso will certainly download lots of other things?

**Comment by pheiduck** [comment]
But I guess the `--compressed` option triggers this issue `url '/stable/core/x86_64/core.db' is invalid`
I will try it without `--compressed`

**Comment by pheiduck** [comment]
Okay, maybe its another issue?:
```
error: url '/stable/core/x86_64/core.db' is invalid
error: failed to setup a download payload for core.db
error: failed to synchronize all databases (invalid url for server)
```

**Comment by pheiduck** [comment]
I will revert the debug commit later.

**Comment by pheiduck** [comment]
> You're missing my point / I haven't been clear enough: you use this action in the context of github actions to build an iso or a kernel respectively. While saving on processing time is always nice, I don't really see a scenario where one profits "really" from this change.

Okay, I see. I will close this then

**Pull request closed without merging**
